# Created by newuser for 5.8.1

zsh_configroot="$HOME/dotfiles/zsh"

srcs=($(find "$zsh_configroot" -name "*.zsh" | sed -z "s/\n/ /g"))

for i in $srcs;do
  source $i
done
autoload -U compinit
compinit
